builds:
- id: ssh-portal-api
  dir: cmd/ssh-portal-api
  binary: ssh-portal-api
  ldflags:
  - >
    -s -w
    -X "main.commit={{.Commit}}"
    -X "main.date={{.Date}}"
    -X "main.goVersion={{.Env.GOVERSION}}"
    -X "main.projectName={{.ProjectName}}"
    -X "main.version={{.Version}}"
  env:
  - CGO_ENABLED=0
  goarch:
  - amd64
  goos:
  - linux
- id: ssh-portal
  dir: cmd/ssh-portal
  binary: ssh-portal
  ldflags:
  - >
    -s -w
    -X "main.commit={{.Commit}}"
    -X "main.date={{.Date}}"
    -X "main.goVersion={{.Env.GOVERSION}}"
    -X "main.projectName={{.ProjectName}}"
    -X "main.version={{.Version}}"
  env:
  - CGO_ENABLED=0
  goarch:
  - amd64
  goos:
  - linux
- id: ssh-token
  dir: cmd/ssh-token
  binary: ssh-token
  ldflags:
  - >
    -s -w
    -X "main.commit={{.Commit}}"
    -X "main.date={{.Date}}"
    -X "main.goVersion={{.Env.GOVERSION}}"
    -X "main.projectName={{.ProjectName}}"
    -X "main.version={{.Version}}"
  env:
  - CGO_ENABLED=0
  goarch:
  - amd64
  goos:
  - linux
