builds:
- &buildDefinition
  id: ssh-portal
  binary: ssh-portal
  main: ./cmd/ssh-portal
  ldflags:
  - >
    -s -w
    -X "main.commit={{.Commit}}"
    -X "main.date={{.Date}}"
    -X "main.goVersion={{.Env.GOVERSION}}"
    -X "main.projectName={{.ProjectName}}"
    -X "main.version={{.Version}}"
  env:
  - CGO_ENABLED=0
  goos:
  - linux
  - darwin
  goarch:
  - amd64
  - arm64
- <<: *buildDefinition
  id: ssh-portal-api
  binary: ssh-portal-api
  main: ./cmd/ssh-portal-api
- <<: *buildDefinition
  id: ssh-token
  binary: ssh-token
  main: ./cmd/ssh-token

changelog:
  use: github-native

sboms:
- artifacts: archive

signs:
- cmd: cosign
  signature: "${artifact}.sig"
  certificate: "${artifact}.pem"
  args:
  - "sign-blob"
  - "--output-signature=${signature}"
  - "--output-certificate=${certificate}"
  - "${artifact}"
  - "--yes"
  artifacts: checksum

dockers:
# ssh-portal
- ids:
  - ssh-portal
  image_templates:
  - "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}/ssh-portal:{{ .Version }}-amd64"
  use: buildx
  build_flag_templates:
  - "--build-arg=BINARY=ssh-portal"
  - "--platform=linux/amd64"
- ids:
  - ssh-portal
  image_templates:
  - "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}/ssh-portal:{{ .Version }}-arm64v8"
  use: buildx
  goarch: arm64
  build_flag_templates:
  - "--build-arg=BINARY=ssh-portal"
  - "--platform=linux/arm64/v8"
# ssh-portal-api
- ids:
  - ssh-portal-api
  image_templates:
  - "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}/ssh-portal-api:{{ .Version }}-amd64"
  use: buildx
  build_flag_templates:
  - "--build-arg=BINARY=ssh-portal-api"
  - "--platform=linux/amd64"
- ids:
  - ssh-portal-api
  image_templates:
  - "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}/ssh-portal-api:{{ .Version }}-arm64v8"
  use: buildx
  goarch: arm64
  build_flag_templates:
  - "--build-arg=BINARY=ssh-portal-api"
  - "--platform=linux/arm64/v8"
# ssh-token
- ids:
  - ssh-token
  image_templates:
  - "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}/ssh-token:{{ .Version }}-amd64"
  use: buildx
  build_flag_templates:
  - "--build-arg=BINARY=ssh-token"
  - "--platform=linux/amd64"
- ids:
  - ssh-token
  image_templates:
  - "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}/ssh-token:{{ .Version }}-arm64v8"
  use: buildx
  goarch: arm64
  build_flag_templates:
  - "--build-arg=BINARY=ssh-token"
  - "--platform=linux/arm64/v8"

docker_manifests:
# ssh-portal
- name_template: "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}/ssh-portal:{{ .Version }}"
  image_templates:
  - "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}/ssh-portal:{{ .Version }}-amd64"
  - "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}/ssh-portal:{{ .Version }}-arm64v8"
- name_template: "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}/ssh-portal:latest"
  image_templates:
  - "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}/ssh-portal:{{ .Version }}-amd64"
  - "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}/ssh-portal:{{ .Version }}-arm64v8"
# ssh-portal-api
- name_template: "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}/ssh-portal-api:{{ .Version }}"
  image_templates:
  - "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}/ssh-portal-api:{{ .Version }}-amd64"
  - "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}/ssh-portal-api:{{ .Version }}-arm64v8"
- name_template: "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}/ssh-portal-api:latest"
  image_templates:
  - "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}/ssh-portal-api:{{ .Version }}-amd64"
  - "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}/ssh-portal-api:{{ .Version }}-arm64v8"
# ssh-token
- name_template: "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}/ssh-token:{{ .Version }}"
  image_templates:
  - "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}/ssh-token:{{ .Version }}-amd64"
  - "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}/ssh-token:{{ .Version }}-arm64v8"
- name_template: "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}/ssh-token:latest"
  image_templates:
  - "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}/ssh-token:{{ .Version }}-amd64"
  - "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}/ssh-token:{{ .Version }}-arm64v8"

docker_signs:
- args:
  - "sign"
  - "${artifact}@${digest}"
  - "--yes"
  artifacts: all
  output: true
