version: 2
builds:
- &buildDefinition
  id: ssh-portal
  binary: ssh-portal
  main: ./cmd/ssh-portal
  ldflags:
  - >
    -s -w
    -X "main.commit={{.Commit}}"
    -X "main.date={{.Date}}"
    -X "main.projectName={{.ProjectName}}"
    -X "main.version=v{{.Version}}"
  env:
  - CGO_ENABLED=0
  goos:
  - linux
  - darwin
  goarch:
  - amd64
  - arm64
- <<: *buildDefinition
  id: ssh-portal-api
  binary: ssh-portal-api
  main: ./cmd/ssh-portal-api
- <<: *buildDefinition
  id: ssh-token
  binary: ssh-token
  main: ./cmd/ssh-token

checksum:
  name_template: checksums.txt

sboms:
- artifacts: archive

changelog:
  use: github-native

dockers_v2:
- id: ssh-portal
  ids:
  - ssh-portal
  images:
  - "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}/ssh-portal"
  tags:
  - "v{{ .Version }}"
  - latest
  build_args:
    BINARY: ssh-portal
- id: ssh-portal-api
  ids:
  - ssh-portal-api
  images:
  - "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}/ssh-portal-api"
  tags:
  - "v{{ .Version }}"
  - latest
  build_args:
    BINARY: ssh-portal-api
- id: ssh-token
  ids:
  - ssh-token
  images:
  - "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}/ssh-token"
  tags:
  - "v{{ .Version }}"
  - latest
  build_args:
    BINARY: ssh-token
