// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/uselagoon/ssh-portal/internal/sshportalapi (interfaces: LagoonDBService,NATSService)
//
// Generated by this command:
//
//	go tool mockgen -destination=sshportalapi_mock_test.go -package=sshportalapi_test -write_generate_directive "-prog_name=go tool mockgen" . LagoonDBService,NATSService
//

// Package sshportalapi_test is a generated GoMock package.
package sshportalapi_test

import (
	context "context"
	reflect "reflect"
	time "time"

	lagoondb "github.com/uselagoon/ssh-portal/internal/lagoondb"
	gomock "go.uber.org/mock/gomock"
)

//go:generate go tool mockgen -destination=sshportalapi_mock_test.go -package=sshportalapi_test -write_generate_directive "-prog_name=go tool mockgen" . LagoonDBService,NATSService

// MockLagoonDBService is a mock of LagoonDBService interface.
type MockLagoonDBService struct {
	ctrl     *gomock.Controller
	recorder *MockLagoonDBServiceMockRecorder
	isgomock struct{}
}

// MockLagoonDBServiceMockRecorder is the mock recorder for MockLagoonDBService.
type MockLagoonDBServiceMockRecorder struct {
	mock *MockLagoonDBService
}

// NewMockLagoonDBService creates a new mock instance.
func NewMockLagoonDBService(ctrl *gomock.Controller) *MockLagoonDBService {
	mock := &MockLagoonDBService{ctrl: ctrl}
	mock.recorder = &MockLagoonDBServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLagoonDBService) EXPECT() *MockLagoonDBServiceMockRecorder {
	return m.recorder
}

// EnvironmentByNamespaceName mocks base method.
func (m *MockLagoonDBService) EnvironmentByNamespaceName(arg0 context.Context, arg1 string) (*lagoondb.Environment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnvironmentByNamespaceName", arg0, arg1)
	ret0, _ := ret[0].(*lagoondb.Environment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EnvironmentByNamespaceName indicates an expected call of EnvironmentByNamespaceName.
func (mr *MockLagoonDBServiceMockRecorder) EnvironmentByNamespaceName(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnvironmentByNamespaceName", reflect.TypeOf((*MockLagoonDBService)(nil).EnvironmentByNamespaceName), arg0, arg1)
}

// SSHKeyUsed mocks base method.
func (m *MockLagoonDBService) SSHKeyUsed(arg0 context.Context, arg1 string, arg2 time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SSHKeyUsed", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// SSHKeyUsed indicates an expected call of SSHKeyUsed.
func (mr *MockLagoonDBServiceMockRecorder) SSHKeyUsed(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SSHKeyUsed", reflect.TypeOf((*MockLagoonDBService)(nil).SSHKeyUsed), arg0, arg1, arg2)
}

// UserBySSHFingerprint mocks base method.
func (m *MockLagoonDBService) UserBySSHFingerprint(arg0 context.Context, arg1 string) (*lagoondb.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserBySSHFingerprint", arg0, arg1)
	ret0, _ := ret[0].(*lagoondb.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UserBySSHFingerprint indicates an expected call of UserBySSHFingerprint.
func (mr *MockLagoonDBServiceMockRecorder) UserBySSHFingerprint(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserBySSHFingerprint", reflect.TypeOf((*MockLagoonDBService)(nil).UserBySSHFingerprint), arg0, arg1)
}

// MockNATSService is a mock of NATSService interface.
type MockNATSService struct {
	ctrl     *gomock.Controller
	recorder *MockNATSServiceMockRecorder
	isgomock struct{}
}

// MockNATSServiceMockRecorder is the mock recorder for MockNATSService.
type MockNATSServiceMockRecorder struct {
	mock *MockNATSService
}

// NewMockNATSService creates a new mock instance.
func NewMockNATSService(ctrl *gomock.Controller) *MockNATSService {
	mock := &MockNATSService{ctrl: ctrl}
	mock.recorder = &MockNATSServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNATSService) EXPECT() *MockNATSServiceMockRecorder {
	return m.recorder
}

// Publish mocks base method.
func (m *MockNATSService) Publish(subj string, data []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", subj, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockNATSServiceMockRecorder) Publish(subj, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockNATSService)(nil).Publish), subj, data)
}
