// Code generated by "enumer -type=SystemLogsType -transform=lower"; DO NOT EDIT.

package lagoon

import (
	"fmt"
	"strings"
)

const _SystemLogsTypeName = "invalidsystemlogstypebuildtask"

var _SystemLogsTypeIndex = [...]uint8{0, 21, 26, 30}

const _SystemLogsTypeLowerName = "invalidsystemlogstypebuildtask"

func (i SystemLogsType) String() string {
	if i < 0 || i >= SystemLogsType(len(_SystemLogsTypeIndex)-1) {
		return fmt.Sprintf("SystemLogsType(%d)", i)
	}
	return _SystemLogsTypeName[_SystemLogsTypeIndex[i]:_SystemLogsTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _SystemLogsTypeNoOp() {
	var x [1]struct{}
	_ = x[InvalidSystemLogsType-(0)]
	_ = x[Build-(1)]
	_ = x[Task-(2)]
}

var _SystemLogsTypeValues = []SystemLogsType{InvalidSystemLogsType, Build, Task}

var _SystemLogsTypeNameToValueMap = map[string]SystemLogsType{
	_SystemLogsTypeName[0:21]:       InvalidSystemLogsType,
	_SystemLogsTypeLowerName[0:21]:  InvalidSystemLogsType,
	_SystemLogsTypeName[21:26]:      Build,
	_SystemLogsTypeLowerName[21:26]: Build,
	_SystemLogsTypeName[26:30]:      Task,
	_SystemLogsTypeLowerName[26:30]: Task,
}

var _SystemLogsTypeNames = []string{
	_SystemLogsTypeName[0:21],
	_SystemLogsTypeName[21:26],
	_SystemLogsTypeName[26:30],
}

// SystemLogsTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func SystemLogsTypeString(s string) (SystemLogsType, error) {
	if val, ok := _SystemLogsTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _SystemLogsTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to SystemLogsType values", s)
}

// SystemLogsTypeValues returns all values of the enum
func SystemLogsTypeValues() []SystemLogsType {
	return _SystemLogsTypeValues
}

// SystemLogsTypeStrings returns a slice of all String values of the enum
func SystemLogsTypeStrings() []string {
	strs := make([]string, len(_SystemLogsTypeNames))
	copy(strs, _SystemLogsTypeNames)
	return strs
}

// IsASystemLogsType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i SystemLogsType) IsASystemLogsType() bool {
	for _, v := range _SystemLogsTypeValues {
		if i == v {
			return true
		}
	}
	return false
}
