// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/uselagoon/ssh-portal/internal/sshserver (interfaces: K8SAPIService,NATSService)
//
// Generated by this command:
//
//	mockgen -package=sshserver_test -destination=sshserver_mock_test.go -write_tool_generate_directive . K8SAPIService,NATSService
//

// Package sshserver_test is a generated GoMock package.
package sshserver_test

import (
	context "context"
	io "io"
	reflect "reflect"

	ssh "github.com/gliderlabs/ssh"
	gomock "go.uber.org/mock/gomock"
)

//go:generate go tool mockgen -package=sshserver_test -destination=sshserver_mock_test.go -write_tool_generate_directive . K8SAPIService,NATSService

// MockK8SAPIService is a mock of K8SAPIService interface.
type MockK8SAPIService struct {
	ctrl     *gomock.Controller
	recorder *MockK8SAPIServiceMockRecorder
	isgomock struct{}
}

// MockK8SAPIServiceMockRecorder is the mock recorder for MockK8SAPIService.
type MockK8SAPIServiceMockRecorder struct {
	mock *MockK8SAPIService
}

// NewMockK8SAPIService creates a new mock instance.
func NewMockK8SAPIService(ctrl *gomock.Controller) *MockK8SAPIService {
	mock := &MockK8SAPIService{ctrl: ctrl}
	mock.recorder = &MockK8SAPIServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockK8SAPIService) EXPECT() *MockK8SAPIServiceMockRecorder {
	return m.recorder
}

// Exec mocks base method.
func (m *MockK8SAPIService) Exec(arg0 context.Context, arg1, arg2, arg3 string, arg4 []string, arg5 io.ReadWriter, arg6 io.Writer, arg7 bool, arg8 <-chan ssh.Window) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exec", arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8)
	ret0, _ := ret[0].(error)
	return ret0
}

// Exec indicates an expected call of Exec.
func (mr *MockK8SAPIServiceMockRecorder) Exec(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exec", reflect.TypeOf((*MockK8SAPIService)(nil).Exec), arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8)
}

// FindDeployment mocks base method.
func (m *MockK8SAPIService) FindDeployment(arg0 context.Context, arg1, arg2 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindDeployment", arg0, arg1, arg2)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindDeployment indicates an expected call of FindDeployment.
func (mr *MockK8SAPIServiceMockRecorder) FindDeployment(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindDeployment", reflect.TypeOf((*MockK8SAPIService)(nil).FindDeployment), arg0, arg1, arg2)
}

// LagoonContainerLogs mocks base method.
func (m *MockK8SAPIService) LagoonContainerLogs(ctx context.Context, namespace, deployment, container string, follow bool, tailLines int64, stdio io.ReadWriter) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LagoonContainerLogs", ctx, namespace, deployment, container, follow, tailLines, stdio)
	ret0, _ := ret[0].(error)
	return ret0
}

// LagoonContainerLogs indicates an expected call of LagoonContainerLogs.
func (mr *MockK8SAPIServiceMockRecorder) LagoonContainerLogs(ctx, namespace, deployment, container, follow, tailLines, stdio any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LagoonContainerLogs", reflect.TypeOf((*MockK8SAPIService)(nil).LagoonContainerLogs), ctx, namespace, deployment, container, follow, tailLines, stdio)
}

// LagoonSystemLogs mocks base method.
func (m *MockK8SAPIService) LagoonSystemLogs(ctx context.Context, namespace, lagoonSystem, jobName string, follow bool, tailLines int64, stdio io.ReadWriter) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LagoonSystemLogs", ctx, namespace, lagoonSystem, jobName, follow, tailLines, stdio)
	ret0, _ := ret[0].(error)
	return ret0
}

// LagoonSystemLogs indicates an expected call of LagoonSystemLogs.
func (mr *MockK8SAPIServiceMockRecorder) LagoonSystemLogs(ctx, namespace, lagoonSystem, jobName, follow, tailLines, stdio any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LagoonSystemLogs", reflect.TypeOf((*MockK8SAPIService)(nil).LagoonSystemLogs), ctx, namespace, lagoonSystem, jobName, follow, tailLines, stdio)
}

// NamespaceDetails mocks base method.
func (m *MockK8SAPIService) NamespaceDetails(arg0 context.Context, arg1 string) (int, int, string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NamespaceDetails", arg0, arg1)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(string)
	ret3, _ := ret[3].(string)
	ret4, _ := ret[4].(error)
	return ret0, ret1, ret2, ret3, ret4
}

// NamespaceDetails indicates an expected call of NamespaceDetails.
func (mr *MockK8SAPIServiceMockRecorder) NamespaceDetails(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NamespaceDetails", reflect.TypeOf((*MockK8SAPIService)(nil).NamespaceDetails), arg0, arg1)
}

// MockNATSService is a mock of NATSService interface.
type MockNATSService struct {
	ctrl     *gomock.Controller
	recorder *MockNATSServiceMockRecorder
	isgomock struct{}
}

// MockNATSServiceMockRecorder is the mock recorder for MockNATSService.
type MockNATSServiceMockRecorder struct {
	mock *MockNATSService
}

// NewMockNATSService creates a new mock instance.
func NewMockNATSService(ctrl *gomock.Controller) *MockNATSService {
	mock := &MockNATSService{ctrl: ctrl}
	mock.recorder = &MockNATSServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNATSService) EXPECT() *MockNATSServiceMockRecorder {
	return m.recorder
}

// KeyCanAccessEnvironment mocks base method.
func (m *MockNATSService) KeyCanAccessEnvironment(arg0, arg1, arg2 string, arg3, arg4 int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "KeyCanAccessEnvironment", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// KeyCanAccessEnvironment indicates an expected call of KeyCanAccessEnvironment.
func (mr *MockNATSServiceMockRecorder) KeyCanAccessEnvironment(arg0, arg1, arg2, arg3, arg4 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "KeyCanAccessEnvironment", reflect.TypeOf((*MockNATSService)(nil).KeyCanAccessEnvironment), arg0, arg1, arg2, arg3, arg4)
}
