name: Tag to Release
on:
  push:
    tags:
    - v*
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: "^1.17"
    - name: Set up environment
      run: echo "GOVERSION=$(go version)" >> $GITHUB_ENV
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v2
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload binaries
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist
  releaseimage:
    strategy:
      matrix:
        binary:
        - service-api
        - ssh-portal
    needs:
    - tag
    - release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Download binaries
      uses: actions/download-artifact@v2
      with:
        name: dist
        path: dist
    - name: Login to GHCR
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Docker metadata
      # this id is namespaced per matrix run
      id: docker_metadata
      uses: docker/metadata-action@v3
      with:
        images: ghcr.io/uselagoon/lagoon-ssh-portal/${{ matrix.binary }}
    - name: Build and push ${{ matrix.binary }} container image
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ steps.docker_metadata.outputs.tags }}
        labels: ${{ steps.docker_metadata.outputs.labels }}
        file: deploy/${{ matrix.binary }}/Dockerfile
        context: dist/${{ matrix.binary }}_linux_amd64
